spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
  profiles:
    include: localstack

oauth:
  endpoint.url: http://localhost:8090/auth
  client:
    id: probation-offender-events-client
    secret: clientsecret

community:
  endpoint.url: http://localhost:8096