version: 2.1

parameters:
  preprod_context:
    type: string
    default: "${CIRCLE_PROJECT_REPONAME}-preprod"
  prod_context:
    type: string
    default: "${CIRCLE_PROJECT_REPONAME}-prod"

orbs:
  hmpps: ministryofjustice/hmpps@1.1.2

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context: << parameters.preprod_context >>
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          context: << parameters.prod_context >>
          requires:
            - request-prod-approval

#  scheduled:
#    triggers:
#      - schedule:
#          cron: "0 7 * * 1-5"
#          filters:
#            branches:
#              only:
#                - main
#    jobs:
#      - hmpps/npm_security_audit
