---
# Values here are the same across all environments
generic-service:
  nameOverride: probation-offender-events

  image:
    repository: quay.io/hmpps/probation-offender-events
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    tlsSecretName: probation-offender-events-cert
    contextColour: green


  env:
    SERVER_PORT: "8080"
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "logstash"
    OFFENDERUPDATEPOLL_ENABLED: "true" 
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    JDK_JAVA_OPTIONS: "-javaagent:/agent/agent.jar"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    probation-offender-events:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "OAUTH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
    probation-offender-events-topic:
      HMPPS_SQS_TOPICS_PROBATIONEVENTS_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_PROBATIONEVENTS_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_PROBATIONEVENTS_ARN: "topic_arn"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: probation-offender-events
