---
# Environment specific values, override helm_deploy/probation-offender-events/values.yaml
generic-service:
  replicaCount: 2
  ingress:
    host: probation-offender-events-staging.hmpps.service.justice.gov.uk
    contextColour: green

  env:
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    COMMUNITY_ENDPOINT_URL: "https://community-api-secure.stage.delius.probation.hmpps.dsd.io"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
